# Generated by Django 4.2.27 on 2025-12-31 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_profile_phone_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('username_attempted', models.CharField(blank=True, help_text='Username attempted (for failed logins)', max_length=150)),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for failed logins)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_us_user_id_5cc93e_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_us_action_fb1cb3_idx'), models.Index(fields=['ip_address', 'timestamp'], name='accounts_us_ip_addr_f56645_idx')],
            },
        ),
    ]
