from rest_framework import serializers
from .models import Supplier, SparePart

class SupplierSerializer(serializers.ModelSerializer):
    class Meta:
        model = Supplier
        
        fields = '__all__' 

class SparePartSerializer(serializers.ModelSerializer):
    
    supplier_name = serializers.ReadOnlyField(source='supplier.supplier_name')

    class Meta:
        model = SparePart
        fields = ['part_id', 'part_name', 'sku_code', 'unit_price', 'current_stock', 'supplier', 'supplier_name']

# Banuka Start
from .models import PurchaseOrder, PurchaseOrderItem, Users

class PurchaseOrderItemSerializer(serializers.ModelSerializer):
    part_name = serializers.ReadOnlyField(source='spare_part.part_name')

    class Meta:
        model = PurchaseOrderItem
        fields = ['item_id', 'spare_part', 'part_name', 'quantity', 'agreed_price']

class PurchaseOrderSerializer(serializers.ModelSerializer):
    items = PurchaseOrderItemSerializer(many=True)
    supplier_name = serializers.ReadOnlyField(source='supplier.supplier_name')

    class Meta:
        model = PurchaseOrder
        fields = ['order_id', 'po_reference_number', 'supplier', 'supplier_name', 'status', 'approved_at', 'delivered_at', 'expected_delivery_date', 'order_date', 'total_amount', 'created_by_user', 'items']
        read_only_fields = ['order_id', 'order_date', 'total_amount']

    def create(self, validated_data):
        items_data = validated_data.pop('items')
        
        # If created_by_user is not provided, try to find a default or handle error
        # For now, if it's missing, let's assume we can't create it without a user, 
        # but in a real app we'd get it from request.user (mapping Django user to Legacy user)
        
        purchase_order = PurchaseOrder.objects.create(**validated_data)
        
        total = 0
        for item_data in items_data:
            # line_total is generated by DB, so we don't pass it
            subtotal = item_data['agreed_price'] * item_data['quantity']
            total += subtotal
            PurchaseOrderItem.objects.create(purchase_order=purchase_order, **item_data)
        
        purchase_order.total_amount = total
        purchase_order.save()
        return purchase_order
# Banuka End