# Generated by Django 4.2.27 on 2026-01-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_purchaseorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False},
        ),
    ]
